### ISSUE TITLE
Expand functional and acceptance test suites

### ISSUE THREAD

**Issue by jamesmillerburgess** [jamesmillerburgess/customer-management#82]
## Todo

- [ ] Cover meteor methods with functional tests using `meteor test`
- [ ] Add database manipulation to acceptance test script
- [ ] Cover basic use cases with acceptance tests
